Dev
Monamimamimamo/Library pull request #4
Opened 2024-10-30 10:02 UTC by Monamimamimamo

Сдаём первую задачу:
https://docs.google.com/document/d/1cC_uKb4M057Rmswq4LEadXz6hAlRLVlDqVIWbGQk4Pk/edit?pli=1&tab=t.0

2024-10-30 15:06 UTC, YaEtoTui commented on src/main/java/com/urfu/library/controller/BookController.java
> +     * @return ResponseEntity с списком книг и статусом HTTP.
со списком*

2024-10-30 15:13 UTC, YaEtoTui commented on src/main/java/com/urfu/library/model/BookRepo.java
> +public interface BookRepo extends JpaRepository<Book, UUID> {
Полное наименование без сокращений

2024-10-30 15:15 UTC, YaEtoTui commented on src/main/java/com/urfu/library/model/Book.java
> +    public void setId(UUID id) {
геттеры и сеттеры должны быть рядом. Я про то что нужно где getId() переносить

2024-10-30 15:26 UTC, YaEtoTui commented on src/test/java/com/urfu/library/controller/BookControllerTest.java
> +public class BookControllerTest {
JavaDoc на все тесты(на все КЛАССЫ тестов)

2024-10-30 15:43 UTC, YaEtoTui commented on src/main/java/com/urfu/library/controller/advice/BookControllerAdvice.java
> +     * Отдает статус 404 Not Found в случае выброса NoSuchElementException
Ребят, 404 ошибка предназначена, когда не найден запрос/ не тот запрос.

2024-10-30 17:06 UTC, YaEtoTui commented on src/main/java/com/urfu/library/model/Book.java
> +    private UUID id;
У меня наверно замечание в том, в одном из запросов вы пытаетесь посмортеть сведение о книге.

Если честно лучше было Integer или Long, Я впервые вижу что бы такое id было и вытаскивали. Ну то есть
вот как будет оно выглядеть
550e8400-e29b-41d4-a716-446655440000 -> и это вы хотите в путь заложить?

2024-10-30 17:08 UTC, YaEtoTui commented on src/main/java/com/urfu/library/controller/BookController.java
> +    public ResponseEntity<Object> getBooksByTitle(@RequestParam String title) {
Я бы указывал List<Book>, зачем Object? И также в остальных, Почему
вы не указываете конкретный класс?

2024-10-30 17:13 UTC, YaEtoTui commented on src/main/java/com/urfu/library/controller/advice/BookControllerAdvice.java
> +    public ResponseEntity<Object> handleException(NoSuchElementException e) {
В данном классе тогда какой смысл от параметров метода? Если не пользуемся

2024-10-30 17:15 UTC, YaEtoTui commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +public class BookServiceTest {
Нет JavaDoc на класс

2024-10-31 03:47 UTC, Monamimamimamo commented on src/main/java/com/urfu/library/controller/BookController.java
> +    public ResponseEntity<Object> getBooksByTitle(@RequestParam String title) {
В этом и ещё одном случае согласен, но есть эндпоинты, в  которых мы возвращаем только статус код, и там вроде как нужно возвращать Object

2024-10-31 14:28 UTC, YaEtoTui commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +public class BookServiceTest {
По требованиям static убираем

2024-10-31 14:31 UTC, YaEtoTui commented
1 задача зачтена

2024-10-31 15:09 UTC, var1etas commented on src/main/java/com/urfu/library/model/Book.java
> +    private UUID id;
поправил

2024-10-31 15:09 UTC, var1etas commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +public class BookServiceTest {
убрал

2024-11-05 19:49 UTC, vpyzhyanov commented
![image](https://github.com/user-attachments/assets/2e17b401-72c1-45a8-b637-87ac755e3add)

Пустой тест, который ничего не делает. Зато тратит кучу времени за запуск спринга.

2024-11-05 20:17 UTC, vpyzhyanov requested changes
Есть замечания.

В целом довольно хорошо структурирован код, каждый класс имеет свою ответственность. Видимо чему-то научили на промышленной разработке)

2024-11-05 20:17 UTC, vpyzhyanov commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +    private Integer bookId;
А не маловато для идентификатора?

2024-11-05 20:17 UTC, vpyzhyanov commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        Assertions.assertThrows(NoSuchElementException.class, () -> bookService.getBookById(2));
Проверка не полная. Проверить тип исключения - недостаточно. Нужно проверять ещё и сообщение об ошибке. Оно может быть разным для исключений одного типа.

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/model/Book.java
> +public class Book {
Каким образом на сдачу попал класс без JavaDoc?

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/model/Book.java
> +    private Integer id;
Не маловато для идентификатора?

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/model/Book.java
> +        return Objects.equals(id, book.id) && Objects.equals(title, book.title) && Objects.equals(author, book.author) && Objects.equals(description, book.description);
однострочное программирование обычно мало кто любит. Запишите каждое условие в отдельную строчку, притом каждая строчка должна начинаться с логического оператора

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/model/Book.java
> +        return Objects.equals(id, book.id) && Objects.equals(title, book.title) && Objects.equals(author, book.author) && Objects.equals(description, book.description);
неужели вы забыли знания полученные в задании на коллекции? Если у книги изменилось описание, то это уже новая книга?

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/model/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Integer> {
Каким образом на сдачу попал класс без JavaDoc?

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/service/BookService.java
> +        bookRepository.save(newBook);
параметр называется `newBook`, а если такая книга уже есть?

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/service/BookService.java
> +            throw new NoSuchElementException();
1. во все места нужно добавить сообщение об ошибке
2. А вы уверены, что это ошибочная ситуация? Мне кажется, что эта ситуация абсолютно нормальна и кидать исключение в этом случае - некорректно. Возвращайте Optional

2024-11-05 20:17 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/service/BookService.java
> +            throw new NoSuchElementException();
во все места нужно добавить сообщение об ошибке
А вы уверены, что это ошибочная ситуация? Мне кажется, что эта ситуация абсолютно нормальна и кидать исключение в этом случае - некорректно. Возвращайте пустой список `List.of()`

Похоже вы пока не понимаете, что такое исключения и как с ними работать.

2024-11-05 20:24 UTC, vpyzhyanov commented
Неработающий код приниматься не будет

![image](https://github.com/user-attachments/assets/a7c41e65-6edd-4a6e-8ba4-d7e3d1523edc)

2024-11-05 20:25 UTC, vpyzhyanov commented
![image](https://github.com/user-attachments/assets/1d5e97bf-5d2a-4fb3-8098-0166215f3bfe)

2024-11-07 06:00 UTC, var1etas commented on src/main/java/com/urfu/library/service/BookService.java
> +        bookRepository.save(newBook);
это мы проверить по идее не сможем, есть книги с одинаковыми авторами и названиями, единственным вариантом было в equals() проверять все три поля, но тогда получается неверно с точки зрения изменения описания, если поменялось=другая книга

2024-11-07 16:15 UTC, Monamimamimamo commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        Mockito.verify(bookRepository, Mockito.times(1)).save(ArgumentMatchers.any(Book.class));
Как я понимаю, когда мы проверяем, что метод не вызвался, нам не откуда брать экземпляр класса, поэтому мы вызываем any и указываем класс, а не экземпляр класса.
Когда мы проверяем, что метод вызвался, нас интересует не просто сам факт задействования класса книги, а её конкретные параметры, на случай не предвиденной логики внутри сервиса.

2024-11-10 17:09 UTC, var1etas commented on pom.xml
> +			<artifactId>hibernate-core</artifactId>
сменили на spring data jdbc

2024-11-10 17:10 UTC, var1etas commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        newBookData.setDescription("Updated Description");
добавили конструктор

2024-11-10 17:10 UTC, var1etas commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +    private Integer bookId;
сменили integer на long

2024-11-10 17:10 UTC, var1etas commented on src/main/java/com/urfu/library/model/Book.java
> +    private Integer id;
сменили integer на long

2024-11-10 17:10 UTC, var1etas commented on src/main/java/com/urfu/library/model/Book.java
> +public class Book {
дописали javadoc

2024-11-10 17:12 UTC, var1etas commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        Assertions.assertThrows(NoSuchElementException.class, () -> bookService.getBookById(2));
убрал исключения, переписал тест

2024-11-10 17:12 UTC, var1etas commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        Assertions.assertEquals(0, result.size());
исправили

2024-11-10 17:13 UTC, var1etas commented on src/main/java/com/urfu/library/model/Book.java
> +        return Objects.equals(id, book.id) && Objects.equals(title, book.title) && Objects.equals(author, book.author) && Objects.equals(description, book.description);
переделали equals и hashcode на Id

2024-11-10 17:14 UTC, var1etas commented on src/main/java/com/urfu/library/model/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Integer> {
дописал javadoc

2024-11-10 17:14 UTC, var1etas commented on src/main/java/com/urfu/library/service/BookService.java
> +            throw new NoSuchElementException();
убрал выбрасывание исключений

2024-11-10 17:17 UTC, var1etas commented on src/main/java/com/urfu/library/service/BookService.java
> +            throw new NoSuchElementException();
убрал выбрасывание исключений, вообще идея бросать и обрабатывать исключения в таких ситуациях пошла из UserDetailService, где в loadUserByUsername() в случае отсутствия юзера в системе выбрасывалось исключение

2024-11-12 20:09 UTC, vpyzhyanov commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        Mockito.verify(bookRepository, Mockito.times(1)).save(ArgumentMatchers.any(Book.class));
да, верно. Только в случае отсутствия вызова нам могут быть известны параметры. Но нас интересует, что метод не будет вызываться при **любых** параметрах, а не только тех, которые мы указали (может мы ошиблись в одним из них и тест будет ложно проходить)

2024-11-12 20:11 UTC, vpyzhyanov commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        Assertions.assertThrows(NoSuchElementException.class, () -> bookService.getBookById(2));
почему убрали исключения?

2024-11-12 20:12 UTC, vpyzhyanov commented on src/test/java/com/urfu/library/service/BookServiceTest.java
> +        Assertions.assertThrows(NoSuchElementException.class, () -> bookService.getBookById(2));
Уж в этом случае исключение было хорошим выбором

2024-11-12 20:20 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/model/Book.java
> +    public Book(Long id, String title, String author, String description) {
не используется

2024-11-12 20:20 UTC, vpyzhyanov commented on src/main/java/com/urfu/library/service/BookService.java
> +        bookRepository.save(newBook);
Вы не поняли. Метод save сохранит **ЛЮБУЮ** книгу. Если она есть, он её изменит, если нет, то создаст. И вы никак это не учитываете и не проверяете. Просто наивно полагая, что если называть переменную `newBook,` то она всегда будет новой. **Но это не так!**. В результате ввели всех в заблуждение, даже себя.

Тут есть 2 варианта. Либо жёстко ограничить метод, т.е. проверять что такой книги ещё нет. Либо не вводить никого в заблуждение некорректными названиями.

P.S. мы всё что угодно можем проверить, было бы желание.

2024-11-12 20:24 UTC, vpyzhyanov approved these changes
Не всё исправлено. Но в целом хорошо. Как исправите оставшиеся замечания, можете мёрджить. Задача принята.

2024-11-14 10:15 UTC, var1etas commented
Все поправили, мержу

2024-11-14 10:15 UTC, merged